### ISSUE TITLE
[WIP] Password change

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/api#3]
I'm not sure if we need this ASSUMING we implement the email change in the correct way. If someone wants to change their password it's a good idea to have a quick change. However, maybe we should send an email confirming this change...

Both ways work... It's a matter of personal preference and not about security (I think...)
So what do you say Fabio? Should we send a verification email? Or since we already have a safe email change we allow passwords to be changed easily and if someone is hacked all they have to do is request a reset?

**Comment by fabiofcferreira** [comment]
I'm working on a _Mail Service_, so that other services (e.g. auth) can use it to send confirmation/verification emails.
