### ISSUE TITLE
Generate random unique id for every account

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/api#4]
Right now we are using emails as a way to identify mentors... This is cool and easy but once you want to change the email in the SQL table things start to get a little wild. It's a better idea to have a UID that does not change while emails can be freely changed.

When you change this you gotta change the information used in the JWT  located at /router/auth.js and /services/token.js

**Comment by fabiofcferreira** [comment]
I'm currently working on a solution for that in the register proccess.
