### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by fabiofcferreira** [upframe/api#49]
We want to welcome our platform mentors by creating a special subdomain for them. In this group of pages, our incredible UX will guide them through:
- [ ] What is Connect and Upframe
- [ ] Password setting
- [ ] Email setting
- [ ] Time slots setting

This issue will be updated during the implementation of all these pages (in [Connect Frontend Repository](https://github.com/ulissesferreira/connect), ) and its corresponding API support.

**Comment by ulissesferreira** [comment]
Let's forget this for now
